### PR TITLE
Fixing FirstPayment, Coupon issues

### LINKED ISSUE #53: Coupon first payment issues
I've tried to create my own coupon, but the documentation is very minimal, so I've basically copied the `FixedDiscountHandler` and changed a few things.

Now my own coupon didn't work, so I applied the default coupon (with the default plan etc.), and I think a lot of things are not working correctly:

- The coupon is not applied during payment, the 10.00 EUR plan remains the same price during checkout.
- After payment I get errors `Trying to get property 'currency' of non-object at ...\\vendor\\laravel\\cashier-mollie\\src\\Order\\Order.php:75`
- There is no subscription created in the database, while the payment has succeeded (probably because of this error in a webhook)
- There is only a payment in the Mollie dashboard with the original price, which is what I also saw during payment

The code I used is the same as in the "documentation" / readme, except I changed the part where I make a new subscription, like this:
```php
$result = $user
            ->newSubscription($name, $plan)
            ->withCoupon('welcome')
            ->create();
```

This is the complete error log:
```
[2019-09-09 13:40:38] local.ERROR: Trying to get property 'currency' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'currency' of non-object at D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\cashier-mollie\\src\\Order\\Order.php:75)
[stacktrace]
#0 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\cashier-mollie\\src\\Order\\Order.php(75): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Trying to get p...', 'D:\\\\GitHub\\\\molli...', 75, Array)
#1 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Concerns\\ManagesTransactions.php(29): Laravel\\Cashier\\Order\\Order::Laravel\\Cashier\\Order\\{closure}(Object(Illuminate\\Database\\SQLiteConnection))
#2 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\DatabaseManager.php(349): Illuminate\\Database\\Connection->transaction(Object(Closure))
#3 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(239): Illuminate\\Database\\DatabaseManager->__call('transaction', Array)
#4 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\cashier-mollie\\src\\Order\\Order.php(102): Illuminate\\Support\\Facades\\Facade::__callStatic('transaction', Array)
#5 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\cashier-mollie\\src\\Order\\Order.php(119): Laravel\\Cashier\\Order\\Order::createFromItems(Object(Laravel\\Cashier\\Order\\OrderItemCollection), Array, false)
#6 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\cashier-mollie\\src\\FirstPayment\\FirstPaymentHandler.php(52): Laravel\\Cashier\\Order\\Order::createProcessedFromItems(Object(Laravel\\Cashier\\Order\\OrderItemCollection), Array)
#7 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Concerns\\ManagesTransactions.php(29): Laravel\\Cashier\\FirstPayment\\FirstPaymentHandler->Laravel\\Cashier\\FirstPayment\\{closure}(Object(Illuminate\\Database\\SQLiteConnection))
#8 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\DatabaseManager.php(349): Illuminate\\Database\\Connection->transaction(Object(Closure))
#9 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(239): Illuminate\\Database\\DatabaseManager->__call('transaction', Array)
#10 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\cashier-mollie\\src\\FirstPayment\\FirstPaymentHandler.php(54): Illuminate\\Support\\Facades\\Facade::__callStatic('transaction', Array)
#11 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\cashier-mollie\\src\\Http\\Controllers\\FirstPaymentWebhookController.php(27): Laravel\\Cashier\\FirstPayment\\FirstPaymentHandler->execute()
#12 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ControllerDispatcher.php(48): Laravel\\Cashier\\Http\\Controllers\\FirstPaymentWebhookController->handleWebhook(Object(Illuminate\\Http\\Request))
#13 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Laravel\\Cashier\\Http\\Controllers\\FirstPaymentWebhookController), 'handleWebhook')
#14 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php(176): Illuminate\\Routing\\Route->runController()
#15 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(680): Illuminate\\Routing\\Route->run()
#16 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#17 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#19 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#20 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#21 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#22 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#23 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#24 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#41 D:\\GitHub\\mollie-subscriptions-5.8-poc\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#42 D:\\GitHub\\mollie-subscriptions-5.8-poc\\public\\index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#43 D:\\GitHub\\mollie-subscriptions-5.8-poc\\server.php(21): require_once('D:\\\\GitHub\\\\molli...')
#44 {main}
```

I think the subscriptions are not saved to my own DB because of this error, this kind of worries me, since we have no control over this and it's hard to debug if a user actually bought a product.

The coupon that's not applied also seems very strange, it might be applied during the next payment, but that's a weird flow, right?

### PR DESCRIPTION
**Pull request by sandervanhooft**
Fixes #53
Fixes #71

### CODE REVIEW

File: src/Coupon/Contracts/CouponHandler.php [hunk 1]
```diff
@@ -28,9 +29,14 @@ public function validate(Coupon $coupon, AcceptsCoupons $model);
      *
      * @param \Laravel\Cashier\Coupon\RedeemedCoupon $redeemedCoupon
      * @param \Laravel\Cashier\Order\OrderItemCollection $items
-     * @return \Laravel\Cashier\Order\OrderItemCollection $items
+     * @return \Laravel\Cashier\Order\OrderItemCollection
      */
     public function handle(RedeemedCoupon $redeemedCoupon, OrderItemCollection $items);
 
-    public function getDiscountOrderItems(RedeemedCoupon $redeemedCoupon, OrderItemCollection $items);
```
Comment (sandervanhooft) [inline src/Coupon/Contracts/CouponHandler.php]: May be a BC, but I don't expect people to have been tinkering with this yet.

File: src/Coupon/Contracts/CouponHandler.php [hunk 2]
```diff
@@ -5,6 +5,7 @@
 use Laravel\Cashier\Coupon\Coupon;
 use Laravel\Cashier\Coupon\RedeemedCoupon;
 use Laravel\Cashier\Exceptions\CouponException;
+use Laravel\Cashier\FirstPayment\Actions\ActionCollection;
```
Comment (SanderMuller) [inline src/Coupon/Contracts/CouponHandler.php]: This use statement isn't used anywhere as far as I can see

Comment (sandervanhooft) [reply src/Coupon/Contracts/CouponHandler.php]: Thanks, I'm cleaning up everything now before release here: #73 .
